export function environmentContributions() {
  return ['API_URL', 'DATABASE_URL', 'POSTGRES_USER', 'POSTGRES_PASSWORD', 'POSTGRES_DB', 'OIDC_ISSUER', 'OIDC_AUDIENCE', 'OIDC_ALGORITHMS', 'OIDC_JWKS_URL', 'CORS_ALLOWED_ORIGINS']
}
