export function augmentSupabaseNativeFiles(files, answers, stack) {
  if (stack.backendKey === 'supabase') {
    files['lib/supabase.ts'] = stack.authentication === 'supabase'
      ? `import { createClient } from '@supabase/supabase-js'\nimport * as SecureStore from 'expo-secure-store'\n\nconst storage = { getItem: SecureStore.getItemAsync, setItem: SecureStore.setItemAsync, removeItem: SecureStore.deleteItemAsync }\nexport const supabase = createClient(process.env.EXPO_PUBLIC_SUPABASE_URL!, process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, { auth: { storage, persistSession: true, autoRefreshToken: true, detectSessionInUrl: false } })\n`
      : `import { createClient } from '@supabase/supabase-js'\n\nexport const supabase = createClient(process.env.EXPO_PUBLIC_SUPABASE_URL!, process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } })\n`
    if (stack.authentication === 'supabase') {
      files['lib/supabase-lifecycle.ts'] = `import { AppState, type AppStateStatus } from 'react-native'\nimport { supabase } from './supabase'\n\nexport function bindSupabaseAuthLifecycle() {\n  const update = (state: AppStateStatus) => {\n    if (state === 'active') supabase.auth.startAutoRefresh()\n    else supabase.auth.stopAutoRefresh()\n  }\n  update(AppState.currentState)\n  const subscription = AppState.addEventListener('change', update)\n  return () => { subscription.remove(); supabase.auth.stopAutoRefresh() }\n}\n`
      files['app/login.tsx'] = `import { useState } from 'react'\nimport { Pressable, StyleSheet, Text, TextInput, View } from 'react-native'\nimport { supabase } from '@/lib/supabase'\n\nexport default function LoginScreen() {\n  const [email, setEmail] = useState('')\n  const [password, setPassword] = useState('')\n  const [error, setError] = useState('')\n  const [pending, setPending] = useState(false)\n  async function signIn() {\n    setPending(true); setError('')\n    const result = await supabase.auth.signInWithPassword({ email: email.trim(), password })\n    if (result.error) setError('Unable to sign in with those credentials.')\n    setPending(false)\n  }\n  return <View style={styles.container}><Text accessibilityRole="header">Sign in</Text>{error ? <Text accessibilityRole="alert">{error}</Text> : null}<TextInput accessibilityLabel="Email" autoCapitalize="none" autoComplete="email" keyboardType="email-address" onChangeText={setEmail} value={email} /><TextInput accessibilityLabel="Password" autoComplete="current-password" onChangeText={setPassword} secureTextEntry value={password} /><Pressable accessibilityRole="button" disabled={pending} onPress={signIn}><Text>{pending ? 'Signing in…' : 'Sign in'}</Text></Pressable></View>\n}\nconst styles = StyleSheet.create({ container: { flex: 1, justifyContent: 'center', padding: 24, gap: 12 } })\n`
      if ((answers.testing || 'basic') !== 'none') files['lib/supabase-lifecycle.test.ts'] = `import { AppState } from 'react-native'\nimport { bindSupabaseAuthLifecycle } from './supabase-lifecycle'\nimport { supabase } from './supabase'\n\njest.mock('./supabase', () => ({ supabase: { auth: { startAutoRefresh: jest.fn(), stopAutoRefresh: jest.fn() } } }))\n\ntest('starts refresh while active and stops it on cleanup', () => {\n  const remove = jest.fn()\n  jest.spyOn(AppState, 'addEventListener').mockReturnValue({ remove } as never)\n  Object.defineProperty(AppState, 'currentState', { configurable: true, value: 'active' })\n  const cleanup = bindSupabaseAuthLifecycle()\n  expect(supabase.auth.startAutoRefresh).toHaveBeenCalled()\n  cleanup()\n  expect(remove).toHaveBeenCalled()\n  expect(supabase.auth.stopAutoRefresh).toHaveBeenCalled()\n})\n`
    }
  }
  return files
}

